name: Generate Blog Entries JSON

on:
  push:
    branches: [ "master" ]
    paths:
      - "blog/**"
  workflow_dispatch:

jobs:
  update-entries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Run Script
        run: python scripts/generate_blog.py

      - name: Commit and push entries
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add blog_entries.json
          git commit -m "Update entries [skip ci]" || echo "No changes"
          git push

